title: nub's blog
description: 
theme: just-the-docs

url: https://hyeonsuim.github.io
search_enabled: false

# External navigation links
nav_external_links:
  - title: Github
    url: https://github.com/HyeonsuIm
# Define Jekyll collections
# collections:
#   # Define a collection named "tests", its documents reside in the "_tests" directory
#   algorithm:
#     permalink: "/:collection/:path/"
#     output: true
#   docker:
#     permalink: "/:collection/:path/"
#     output: true

# just_the_docs:
#   # Define which collections are used in just-the-docs
#   collections:
#     # Reference the "tests" collection
#     algorithm:
#       # Give the collection a name
#       name: algorithm
#       nav_fold: true
#       # Exclude the collection from the navigation
#       # Supports true or false (default)
#       # nav_exclude: true
#       # Fold the collection in the navigation
#       # Supports true or false (default)
#       # nav_fold: true
#       # Exclude the collection from the search
#       # Supports true or false (default)
#       # search_exclude: true
#     docker:
#       name: docker
#       nav_fold: true